### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#1]
很棒的 app，已经付费支持。
提几个建议：
1. 隐藏主界面
2. Python 的路径改为可修改

**Comment by xudaolong** [comment]
@Macr0phag3  谢谢你的支持。对于你是第一个用户，这个无条件完成。哈哈哈。这两周内我更新。

**Comment by Macr0phag3** [comment]
我指的隐藏主界面是像 dash 那样，Docker 里都没有的那种
然后还有几个问题想问：
- 你的付费机制是一次性的吧？建议在 Pricing 里详细说明一下。
- 设置里的 `指令响应键` 和 `跳转指令键` 的用法是？

还有 2 个建议：
- 退出登录能不能加个确认框，不小心就退出了
- 下面这个地方建议把扩展名去了，改为对应的 logo
![image](https://user-images.githubusercontent.com/20874963/54873199-6dc96500-4e0c-11e9-85d3-59178e36e926.png)
这个地方就做的很好：
![image](https://user-images.githubusercontent.com/20874963/54873209-8c2f6080-4e0c-11e9-8df8-3b131c523a10.png)
但是还是有扩展名

**Comment by xudaolong** [comment]
@Macr0phag3 
- 你的付费机制是一次性的吧？建议在 Pricing 里详细说明一下。
  - 这个当然是永久一次性的
- 设置里的 指令响应键 和 跳转指令键 的用法是？
  - emm. 我加一个指引说明

- 退出登录能不能加个确认框，不小心就退出了
   - 这个可以有
- 下面这个地方建议把扩展名去了，改为对应的 logo（扩展名比较冗余，如果是我的话，不管加不加 logo，扩展名我一定不加）
   - 这个我考虑下.

谢谢建议哈

**Comment by Macr0phag3** [comment]
懂了懂了。哈哈我还找了半天怎么把 tab 键加进去，原来用指令相应键就行了

**Comment by xudaolong** [comment]
Duplicate of #6

**Comment by xudaolong** [comment]
@Macr0phag3 更新了，片段列表有图标啦

**Comment by Macr0phag3** [comment]
> @Macr0phag3 更新了，片段列表有图标啦

cool
