### ISSUE TITLE
windows登录不上，授权按钮是灰色的

### ISSUE THREAD

**Issue by shijy675497282** [oncework/codeexpander#10]
windows登录不上，授权按钮是灰色的
win10

**Comment by xudaolong** [comment]
@shijy675497282 你下载的是2.7.4版本吗？截图看看

**Comment by shijingyu** [comment]
不知道多少版本 v2ex来的。 点更新版本 提示是最新的。

![image](https://user-images.githubusercontent.com/18032450/55164822-5214e480-51a7-11e9-9a9b-a603616a2392.png)

**Comment by shijingyu** [comment]
已解决， 2.7.4解决了问题

**Comment by xudaolong** [comment]
@shijingyu 好的~
