### ISSUE TITLE
代码格式改进

### ISSUE THREAD

**Issue by yunayj** [oncework/codeexpander#101]
1. 希望能丰富一下代码颜色，使代码更好看一点
![image](https://user-images.githubusercontent.com/61784125/183631038-2a926d22-0c90-4615-8331-a7e5e5c142fc.png)
2. 一个中文会占位两个空格，希望能优化一下代码的格式，统一一下间距
![image](https://user-images.githubusercontent.com/61784125/183631384-d1ba10aa-2cff-4d3d-943f-119fd037b5d0.png)

**Comment by xudaolong** [comment]
@yunayj  同 #95 ，间距可以用 
<img width="454" alt="image" src="https://github.com/oncework/codeexpander/assets/9654838/0d644bd0-589c-47d8-b02b-be74d02db3a5">
