### ISSUE TITLE
软件开机自启后无代码片段

### ISSUE THREAD

**Issue by yunayj** [oncework/codeexpander#102]
如果软件在开机后自启前没有及时联网，并且网络可用的话，会出现图中的问题，代码片段以及登录状态都会消失
![9849ff6da7e2dd7dbe176958d49505b](https://user-images.githubusercontent.com/61784125/183638312-1bb272ac-d147-4f55-8c9e-f722262c95d0.jpg)

**Comment by xudaolong** [comment]
@yunayj  后面改到有网络的时候进行登录校验
