### ISSUE TITLE
希望在搜索框添加使用缩略语的功能

### ISSUE THREAD

**Issue by inltd** [oncework/codeexpander#103]
比如输入 dx abc 调用定义的大写脚本, 返回 ABC 的结果, Enter复制到剪贴板

**Comment by xudaolong** [comment]
@inltd 现在支持 内容，后续增加一个 复制结果吧 
<img width="500" alt="image" src="https://github.com/oncework/codeexpander/assets/9654838/fddacfac-f732-4169-be2d-72e250144512">

**Comment by xudaolong** [comment]
#133
