### ISSUE TITLE
希望能够修改快捷键或关闭快捷键

### ISSUE THREAD

**Issue by yunayj** [oncework/codeexpander#106]
希望能修改或关闭这个快捷键，有时候快捷键冲突很难受
![image](https://user-images.githubusercontent.com/61784125/203473785-b2f069b6-e69f-4ec8-80e1-5d1bf6c426ec.png)

**Comment by xudaolong** [comment]
@yunayj 这个可以修改的呀 在输入框 你再按其他按键

**Comment by yunayj** [comment]
抱歉，我发现可以修改，但不能关闭，能不能增加这个选择

**Comment by yunayj** [comment]
> 

抱歉，我发现可以修改，但不能关闭，能不能增加这个选择

**Comment by xudaolong** [comment]
@yunayj 好的

**Comment by xudaolong** [comment]
同 #95
