### ISSUE TITLE
新建片段，鼠标拖动全选文字时，如果鼠标划出窗口，新建窗口会被关闭

### ISSUE THREAD

**Issue by UniqueSimon** [oncework/codeexpander#11]
当新建一个片段的时候，因为会把剪切板的内容自动加入，所以用鼠标滑动全选想删除。
滑动出窗口时，整个窗口就自动关闭了。

![QQ20190329-093207.gif](https://i.loli.net/2019/03/29/5c9d7e920d691.gif)

**Comment by xudaolong** [comment]
@UniqueSimon emmm... 因为mask遮罩检测到了鼠标释放的事件。晚点我屏蔽掉这层事件好了。谢谢啦

**Comment by UniqueSimon** [comment]
@xudaolong 提bug的话，放一个issue好还是一个bug一个issue好啊？其实我还有一些要提，我怕提太多你不开心

**Comment by xudaolong** [comment]
@UniqueSimon 不会呀 你每个提吧 反正这个产品就我一个人 没啥测试人员 哈哈哈

**Comment by xudaolong** [comment]
@UniqueSimon 已修复。等待下次热更新。
