### ISSUE TITLE
文字表达错误，应显示复制代码片段内容，而不是已复制代码片段内容。同时希望列表可以显示片段的类型信息。

### ISSUE THREAD

**Issue by kunrui** [oncework/codeexpander#121]
![image](https://user-images.githubusercontent.com/18269031/215937570-38fa9d47-d643-4452-9af7-f9212b0efcdf.png)

**Comment by xudaolong** [comment]
![image](https://user-images.githubusercontent.com/9654838/226787590-f868bd5c-662e-4e49-b498-511addd4ddb7.png)
