### ISSUE TITLE
搜索片段大英文小写区分导致片段名字大小写不一样而无法查询出来

### ISSUE THREAD

**Issue by szy2k** [oncework/codeexpander#123]
搜索片段大英文小写区分导致片段名字大小写不一样而无法查询出来

建议添加一个选项是否匹配分大小写查询,,或者直接忽略大小写.谢谢!

**Comment by xudaolong** [comment]
@szy2k 
<img width="356" alt="image" src="https://github.com/oncework/codeexpander/assets/9654838/65f0329c-f5a6-4901-b13b-bd1e0c766f51">

跟下个版本
