### ISSUE TITLE
不兼容本地用户搬迁的问题

### ISSUE THREAD

**Issue by Tianming72** [oncework/codeexpander#124]
现在有一个问题，我原来是不连接云端的，积累了一些代码片段，现在我用云端账户登录后，原来的代码片段就没了；
我进行了备份恢复，恢复后原来的代码片段就有了，但是显示我没有登录云端账户，我登录云端账号后，代码片段又没了

**Comment by xudaolong** [comment]
@Tianming72 同 #98，后续支持仅导出片段
