### ISSUE TITLE
最小化隐藏图标bug

### ISSUE THREAD

**Issue by qirui1** [oncework/codeexpander#125]
1.点击任务栏图标的最小化之后，dock的图标和app的界面一同隐藏（正常）
2.快捷键调用之后，弹出文本搜索框的同时，图标会弹出来（正常情况，此时图标是不是不应该弹出），并且粘贴完之后文本搜索框消失，但是图标依然存在。
3.第二次调用快捷键之后，粘贴之后，页面会弹出来，并且不再隐藏（正常情况是不是应该图标与页面同时隐藏）。

**Comment by xudaolong** [comment]
@qirui1 已修复 跟下个版本
