### ISSUE TITLE
English? lol

### ISSUE THREAD

**Issue by YouveGotMeowxy** [oncework/codeexpander#126]
Hi

Just installed for the first time and it's all in Chinese. I can't even understand the UI enough to find an Options area to see if I can switch to English?

- For now, can someone screenshot where to do so?
- For later, can the installer or app itself auto-detect the language/locale from the system and set the app to use it?

**Comment by xudaolong** [comment]
@YouveGotMeowxy You can shortcut cmd + ,
<img width="1101" alt="image" src="https://github.com/oncework/codeexpander/assets/9654838/a84d8171-a9f4-4b0f-9d89-d0d2e9754e3b">
