### ISSUE TITLE
片段中的光标占位符定位不准确

### ISSUE THREAD

**Issue by Xzavier0722** [oncework/codeexpander#128]
当光标定位符跟在一个空格后面时，光标会定位在空格前面。
例如以下代码片段：
```java
public String %c%() {
    return "";
}
```
可以看到占位符在 ```String{空格}{占位符}()```，预期结果为光标在括号前空格后。但是实际执行结果是光标在g字母之后，空格之前:
![image](https://github.com/oncework/codeexpander/assets/35729653/ac23d86b-2525-4e3d-97f3-4a4a1914b839)

经测试该问题在本case下必现。

**Comment by xudaolong** [comment]
@Xzavier0722 后续增加精确定位的配置 补充 #133
