### ISSUE TITLE
激活码激活后请隐藏激活码等问题

### ISSUE THREAD

**Issue by Fansur1** [oncework/codeexpander#129]
1. 激活码激活后隐藏激活码；
2. 支持反激活操作
3. 将含有"/"字符作为缩略语时，将致使快捷输出功能失效。

**Comment by xudaolong** [comment]
@Fansur1 
1. 可以
2. 后台自动反激活
3. 第三个功能为啥要这样，现在默认是非下面符号都会取消的。

<img width="569" alt="image" src="https://github.com/oncework/codeexpander/assets/9654838/aac16ead-b47c-475e-b602-2d71f0e3525a">

**Comment by xudaolong** [comment]
功能补充到 #133
