### ISSUE TITLE
当触发缩略语时，可以弹出预览气泡

### ISSUE THREAD

**Issue by haikerapples** [oncework/codeexpander#132]
【背景】
当很多相似的缩略语时，或者缩略语比较多时，预览就很重要了

【功能期望】
当触发缩略语时，可以弹出预览气泡（类似于dash的做法），然后Enter了后，才粘贴到目标位置；以下是dash的snippets的触发缩略语的效果，希望可以实现下

![image](https://github.com/oncework/codeexpander/assets/27751726/13f4be45-474f-4ed4-8f10-3f7f3ccfffcb)

**Comment by xudaolong** [comment]
@haikerapples 补充到 #133
