### ISSUE TITLE
无法运行python代码

### ISSUE THREAD

**Issue by oijqws** [oncework/codeexpander#134]
![image](https://github.com/oncework/codeexpander/assets/38936048/e629de0f-d154-49af-9fd9-41ef5efc282e)
![image](https://github.com/oncework/codeexpander/assets/38936048/36d36fdf-fc9e-4d74-bce7-f2c2b0e59ee8)

**Comment by oijqws** [comment]
我python版本是3.11

**Comment by xudaolong** [comment]
@oijqws 已修复 4.3.5
