### ISSUE TITLE
登录码云后之前创建的短语全部丢失

### ISSUE THREAD

**Issue by PercivalTang** [oncework/codeexpander#135]
尝试了几天才购买了正式版，很好用的软件！但是发现一个不知道是不是恶性bug的问题！
我在登录码云之前已经创建了十几个短语，但今天准备开启同步，登录码云之后，那十几条短语乃至分组全部丢失，分组和短语都变成0了，退出登录也无法恢复，就这么不见了！请问这是什么情况？
顺便，我是今天为了CodeExpander码云同步，刚注册的码云新账号，之前从没有用码云同步过，没想到刚登陆就遇到了这样的问题，太糟心了……
现在有点不太敢用了！万一记录了几十上百条短语之后再给我丢失一次，想死的心都有！好在这次也就丢失了十几条短语……

**Comment by xudaolong** [comment]
@PercivalTang 那个开启同步是从码云拉下来的并清空当前的，如果短语在未联网的时候创建，这个时候还未上传到码云，会被清空掉。

不过不用担心，默认有开启备份功能的。你打开备份功能查看即可，后续我优化这个同步的逻辑。
