### ISSUE TITLE
去掉片段的指令或者清空代码后，直接点删除，有时会删不掉并提示“本地片段已损坏,请从云端更新”

### ISSUE THREAD

**Issue by UniqueSimon** [oncework/codeexpander#14]
去掉片段的指令，或者清空片段的代码时，直接删除，有时会触发。
删不掉的片段，点击已经显示不出详细页面了，再次点击删除会提示“本地片段已损坏,请从云端更新”。
从网页端看，片段已经没了；客户端点同步全部，也不能删除。
只能清空CodeExpander文件夹下的文件，重新登录再同步才能去除。
![Snipaste-20-43-01.png](https://i.loli.net/2019/03/29/5c9e13a40cf31.png)

也不是每次都能触发这个bug，有时触发了过一会错误的片段也会消失。

但有一个可以100%触发删不掉这个bug的操作：把CodeExpander文件夹下片段对应的文件删了。

**Comment by xudaolong** [comment]
@UniqueSimon =。= 因为点删除前会去找这个文件是否存在去删除。你把文件夹都删了。肯定不会删了。

- 如果是这个提示，我将该文件从列表中删除掉。

**Comment by UniqueSimon** [comment]
@xudaolong 发现所有会触发上传的操作都不能退出编辑页面，比如重命名/改代码/改指令/改类型。
如果在同步完毕前切换到其他的片段或者进行删除操作。
那这个片段再打开一定会变成“本地片段已损坏,请从云端更新”。

有时这个同步很迷，我改完后缀名，列表栏的后缀名过好久都不会变，这时候我只要切换片段，这个片段就悲剧了。

**Comment by xudaolong** [comment]
@UniqueSimon 自动同步 =。= 这么奇怪的吗 我这边没问题。。你那边估计是连接 github 超时了。

**Comment by xudaolong** [comment]
@UniqueSimon 修复白板问题 你再试试

**Comment by UniqueSimon** [comment]
@xudaolong ![Snipaste-15-20-51.png](https://i.loli.net/2019/03/30/5c9f1914caaeb.png)
好像没变化

**Comment by xudaolong** [comment]
@UniqueSimon 未能重现哦。你弄个gif我看看，我将在网络这个方面加些判断。

**Comment by UniqueSimon** [comment]
@xudaolong 指令可以选填之后没碰到过了

**Comment by xudaolong** [comment]
@UniqueSimon 哦哦哦 好的。
