### ISSUE TITLE
Python 的编码问题

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#15]
见图
![image](https://user-images.githubusercontent.com/20874963/55275774-0b99c400-5326-11e9-8f20-8f93ec59f924.png)

![image](https://user-images.githubusercontent.com/20874963/55275776-13f1ff00-5326-11e9-8dff-b1397244eeb1.png)

**Comment by xudaolong** [comment]
@Macr0phag3 2.7.9修复此问题。

**Comment by Macr0phag3** [comment]
问题依然存在：
![image](https://user-images.githubusercontent.com/20874963/55277527-37c03f80-533c-11e9-88ef-ada582c95ed5.png)

配置如下：
![image](https://user-images.githubusercontent.com/20874963/55277532-4870b580-533c-11e9-8065-92f084aa54ec.png)

![image](https://user-images.githubusercontent.com/20874963/55277534-50305a00-533c-11e9-9254-e4577e4c70a0.png)

**Comment by xudaolong** [comment]
Python3 版本，请设置你的环境变量：

https://stackoverflow.com/questions/36651680/click-will-abort-further-execution-because-python-3-was-configured-to-use-ascii?utm_medium

查看编码
```python
import locale
import codecs
print(locale.getpreferredencoding())
print(codecs.lookup(locale.getpreferredencoding()).name)
```
![image](https://user-images.githubusercontent.com/9654838/55277785-ebc2ca00-533e-11e9-9403-315c8d763232.png)

**Comment by Macr0phag3** [comment]
一样
![image](https://user-images.githubusercontent.com/20874963/55277826-4825e980-533f-11e9-99b8-6f0b06654a87.png)

**Comment by xudaolong** [comment]
设置这两个为全局变量呢？

```
export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
```

![image](https://user-images.githubusercontent.com/9654838/55278099-1151d280-5343-11e9-85d1-29e23fce6853.png)

**Comment by Macr0phag3** [comment]
一样
![image](https://user-images.githubusercontent.com/20874963/55278144-80c7c200-5343-11e9-8d84-475d6a73008e.png)

也是会报错

**Comment by Macr0phag3** [comment]
可能的解决方案
https://blog.csdn.net/u011415481/article/details/80794567

顺便提一下，我发现你这里运行 Python3 的shell 没有载入我设置的环境变量
```
import sys
import os

print(sys.stdout.encoding)

print(os.getenv('PWD'))
```

![image](https://user-images.githubusercontent.com/20874963/55287209-802d3b00-53d8-11e9-8a20-e31d84a006a7.png)

**Comment by Macr0phag3** [comment]
解决了：
报错环境：pyenv 安装的py3.x，需要在`~/.pyenv/shims`中的`export PYENV_ROOT....`下加上：
```
 export LC_ALL=zh_CN.UTF-8
 export LANG=zh_CN.UTF-8
```

**Comment by xudaolong** [comment]
这样也是可以的.

```
import io
import sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')
print('解决问题')
```
