### ISSUE TITLE
2 个 bug

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#16]
1. 这两个按钮失效
![image](https://user-images.githubusercontent.com/20874963/55288053-83c6bf00-53e4-11e9-8780-1fe91dd14928.png)

2. 在使用 `⎇+空格` 的时候，没有配置指令的 snippet 无法放入剪贴板
![image](https://user-images.githubusercontent.com/20874963/55288102-54fd1880-53e5-11e9-9b31-aec0e50f2568.png)

**Comment by xudaolong** [comment]
@Macr0phag3 1.修复 2.未能重现

**Comment by Macr0phag3** [comment]
第2条重启电脑后解决了

**Comment by xudaolong** [comment]
@Macr0phag3 竟然要重启电脑这大招...ヽ(*。>Д<)o゜可怕
