### ISSUE TITLE
建议横向滚动条加粗一点

### ISSUE THREAD

**Issue by UniqueSimon** [oncework/codeexpander#17]
MacOS下太细了，很容易就变成拉伸窗口或者移动窗口了

**Comment by xudaolong** [comment]
@UniqueSimon emm... macos有触摸板鸭， 你两只手指向右不就可以滚动了。。我找个时间优化一下。

**Comment by UniqueSimon** [comment]
@xudaolong 哈哈，怕键盘艹坏，我盖了张A4纸

**Comment by xudaolong** [comment]
@UniqueSimon 加大了呢. 你看看 最近开发别的功能去了。
