### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by erm3nda** [oncework/codeexpander#19]
So you call this cross-platform when there's no way to install in Linux?
The term you should use is "bi-platform" at max.

**Comment by xudaolong** [comment]
I can support Linux if needed and if someone is willing to help, because I have no test environment in Linux.

**Comment by erm3nda** [comment]
I found Gisto in the meanwhile.

Anyway, if you feel good expanding your software to Linux, i will test it
at least.
Also, want to ask if you have some CI to make your life easier when
updating code to avoid people testing little things.

Kind regards.

~~ Self signed ~~

**Comment by xudaolong** [comment]
Thank you for your advice. I will test it soon. Gisto is slightly different from my function, and some functions call the interface at the bottom of the system.
