### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by coolrc136** [oncework/codeexpander#2]
系统win10 1809，进入登陆页面后authorize按钮是灰色的
![image](https://user-images.githubusercontent.com/11882183/54896298-78fcbd80-4efe-11e9-92a3-ea63a7494461.png)

**Comment by xudaolong** [comment]
@coolrc136 等等我晚上回去更新版本哈 不着急

**Comment by xudaolong** [comment]
@coolrc136 已更新。查看 release， 兄弟。
