### ISSUE TITLE
做任何操作都提示「请登录后操作……」

### ISSUE THREAD

**Issue by JokerQyou** [oncework/codeexpander#20]
仓库首页显示 `Most features are free and buy now for $4.99 if you want to support the author` 所以我想先试试。但是登录后，无法进行任何操作。

1. 当尝试同步 Gist 时（全部同步 / 从云端更新 / 上传）
![image](https://user-images.githubusercontent.com/1465267/61728756-6610d180-ada8-11e9-8946-8f797f0deb9c.png)

2. 当点击`+`按钮，尝试创建片段时
![image](https://user-images.githubusercontent.com/1465267/61728841-8ccf0800-ada8-11e9-9aaa-70ac9f1fa6d5.png)

3. 当点击`+`按钮，尝试创建分组时
![image](https://user-images.githubusercontent.com/1465267/61728873-9c4e5100-ada8-11e9-9a64-e9c969dc834f.png)

4. 即使已经登录，菜单上仍然有「个人登录」这个菜单项
![image](https://user-images.githubusercontent.com/1465267/61728916-b5ef9880-ada8-11e9-91e7-a95ded4fff7a.png)

5. 尝试在已登录状态下，再次点击菜单的「个人登录」
![image](https://user-images.githubusercontent.com/1465267/61728976-da4b7500-ada8-11e9-99cd-57863cc4f5a2.png)

6. 版本信息（不知道在哪里查看版本信息，也没找到「关于」菜单，猜测这个「更新日志」里面的可能是版本信息？）
![image](https://user-images.githubusercontent.com/1465267/61729033-fa7b3400-ada8-11e9-9d8e-13f0f6e94ac7.png)

**Comment by JokerQyou** [comment]
补充：重启应用后，登录状态被清空，又需要重新登录。但是登录后又无法进行任何操作。
![image](https://user-images.githubusercontent.com/1465267/61729393-aae93800-ada9-11e9-9c21-a96a10e6e951.png)

**Comment by xudaolong** [comment]
@JokerQyou 你可以加一下我的微信 细节聊一下吗

**Comment by xudaolong** [comment]
@JokerQyou 能否上传一个gif我看看 到底啥情况呀~ 我刚刚测试是可以的

**Comment by JokerQyou** [comment]
Sorry，不使用微信……是还需要什么其他信息吗？我可以在这里补充。

**Comment by xudaolong** [comment]
@JokerQyou 登陆之后 如果你的gist 内容多的话 下载的时间会比较长 或者网络的原因...

**Comment by xudaolong** [comment]
@JokerQyou 如果还存在个人登陆情况 证明登陆不成功的

**Comment by JokerQyou** [comment]
我可以正常访问 Gist，并且可以正常进行登录、授权，应该可以排除网络原因。Gist 数量很少。
![image](https://user-images.githubusercontent.com/1465267/61729980-036d0500-adab-11e9-845f-ab4c96b8d184.png)

**Comment by xudaolong** [comment]
@JokerQyou 可以使用LICEcap录制个gif我吗？ 我刚刚的操作...
![image](https://user-images.githubusercontent.com/9654838/61730146-5c3c9d80-adab-11e9-8cf1-036d6ae5c5ce.png)

**Comment by JokerQyou** [comment]
登录界面没有录制，这是登录之后的操作。
![Untitled](https://user-images.githubusercontent.com/1465267/61730417-e8e75b80-adab-11e9-8f3e-afdd0a2da25e.gif)

**Comment by xudaolong** [comment]
@JokerQyou 你查看 ``~/Documents/codeexpander`` 是否有文件？

**Comment by JokerQyou** [comment]
有
![image](https://user-images.githubusercontent.com/1465267/61730780-ad00c600-adac-11e9-9143-2ee9f5448883.png)

**Comment by xudaolong** [comment]
@JokerQyou 嗯 缺少了部分文件 你打开 ``cmd + shift + 8 `` 开发者模式 ，查看console 有什么error?

**Comment by JokerQyou** [comment]
![image](https://user-images.githubusercontent.com/1465267/61730990-1a145b80-adad-11e9-98df-8263813cce11.png)

**Comment by xudaolong** [comment]
@JokerQyou 还有其他不一样错误吗 我稍后打包一份最新版本。

**Comment by JokerQyou** [comment]
没有了，后面都是一样的。

**Comment by JokerQyou** [comment]
![image](https://user-images.githubusercontent.com/1465267/61731245-9dce4800-adad-11e9-9ec1-32eb6fc3dd31.png)
中间有一段不一样的。

**Comment by xudaolong** [comment]
@JokerQyou  正在发布个hotfix...

**Comment by xudaolong** [comment]
@JokerQyou 若不行可以再看一下console吗？

**Comment by JokerQyou** [comment]
已经更新，并且重启后重新登录了，似乎没有什么变化。
![image](https://user-images.githubusercontent.com/1465267/61732497-4f6e7880-adb0-11e9-8478-4007e178a659.png)

**Comment by JokerQyou** [comment]
尝试了一下配置代理（其实没有必要，浏览器走系统代理都可以正常访问 Gist），也没有效果。我明天再尝试了。

**Comment by xudaolong** [comment]
@JokerQyou 好的。。早点睡吧

**Comment by xudaolong** [comment]
@JokerQyou 可以了 你再次更新下。
