### ISSUE TITLE
Cannot Remove Group if Group Name is Too Long

### ISSUE THREAD

**Issue by bigdoodr** [oncework/codeexpander#21]
If a snippet group is created with a long name (for example, I created "Linux search commands"), the end of the name is replaced by ellipsis ("Linux search comm..."). The group's menu button becomes inaccessible.

**Comment by xudaolong** [comment]
@bigdoodr I will solve this problem as soon as possible. Thank you.

**Comment by xudaolong** [comment]
@bigdoodr Fix in 2.9.17 version. Please update to the latest version.
