### ISSUE TITLE
Problem with Login Github

### ISSUE THREAD

**Issue by luisramirez-m** [oncework/codeexpander#23]
Hello,

When installing and after logging with github, and I clicked on "Update current snippets from Gist" (icon), the message "Please log in and operate .." appears.

Seeing other issues in this repository, I found that you can see the console for debug and this is the error:

![code-expander](https://user-images.githubusercontent.com/25333374/71934743-63166b80-31a5-11ea-8c86-6330c2346761.png)

I think is a problem with Github or my account. Extra information:

- Windows 10
- My github account uses double authentication

If you need more information, you can tell me.

Excuse my English

**Comment by xudaolong** [comment]
@luisramirez-m  Good morning, this problem is simply solved, you can update the version to 3.1.15, and you should be able to log in again. 
Waiting for good news. 😀

**Comment by luisramirez-m** [comment]
Hello, it works. Thanks for the update and application!
