### ISSUE TITLE
用触控板，轻点工具栏之后，界面会随光标移动

### ISSUE THREAD

**Issue by diklios5768** [oncework/codeexpander#24]
双击或者按下触控板才能取消，基本上按到下载上传或者设置都会触发，非常影响操作。不知道是不是 10.15 的系统问题。

**Comment by diklios5768** [comment]
还有一个问题，windows下点工具栏就会直接放大整个软件界面，但是有最大的限制，似乎是全屏的大小。点全屏之后不会出现问题。

**Comment by xudaolong** [comment]
@diklios5768 windows下点工具栏？ windows系统?

**Comment by diklios5768** [comment]
@xudaolong 是的，两个系统我都测试了，Windows 也是工具栏的问题，但是是放大到桌面大小就会停止。

**Comment by xudaolong** [comment]
@diklios5768 你windows是啥系统 我也是win10 和 win7 都没问题

**Comment by diklios5768** [comment]
![问题](https://user-images.githubusercontent.com/47837462/75602949-f6648100-5b04-11ea-9574-0d7b444d5185.gif)

**Comment by diklios5768** [comment]
不好意思，最近有点事情，反馈慢了，我是win10系统，版本号1903，之前Mac系统是10.15.3Catalina

**Comment by xudaolong** [comment]
@diklios5768 我也是 1903 然后我升级到 1909 也没问题 我换个方法解决吧...

![](https://s2.ax1x.com/2020/03/03/3fqih8.gif)

**Comment by xudaolong** [comment]
@diklios5768 解决了 已更新至3.2.5 window的

**Comment by ivanberry** [comment]
mac 10.15下复现了，未登录时，最右侧按钮hover态时，会出现随光标移动

**Comment by xudaolong** [comment]
@ivanberry 这应该另外一种情况 预计今晚会有版本修复哈

**Comment by xudaolong** [comment]
@ivanberry 3.3.5版本已更新

**Comment by diklios5768** [comment]
macos15.14版本，软件 3.3.6 版本，触控板设置可以单指轻点，点击工具栏，依旧会出现窗口随光标移动的 bug，只有按下触控板，才会取消随光标移动。
