### ISSUE TITLE
点击上传操作，报错。mac os 10.14

### ISSUE THREAD

**Issue by Switch-vov** [oncework/codeexpander#26]
![image](https://user-images.githubusercontent.com/11993575/75103997-18aa5a80-563e-11ea-9076-0e1d02b9e06a.png)

**Comment by xudaolong** [comment]
@Switch-vov 修改过得配置才能上传

**Comment by Switch-vov** [comment]
@xudaolong 我重启了一下就好了。如果这种操作有问题，看看能不能加些人性化提示。

**Comment by xudaolong** [comment]
@Switch-vov 噢噢噢 我加个提示咯
