### ISSUE TITLE
删除Fill-ins，无法预览

### ISSUE THREAD

**Issue by Laxenade** [oncework/codeexpander#28]
复现(Windows):
* 打开Fill-ins后，就算全部删除，预览也会显示“无法预览”。
* 同样是Fill-ins的另一个问题：插入一个Fill-in之后以后打的所有字都会有和Fill-in一样的highlight (绿底)

**Comment by xudaolong** [comment]
@Laxenade 第一个重现不了 如果可以的话 可以弄个gif 我看看哈

**Comment by Laxenade** [comment]
https://i.loli.net/2020/03/15/3hgnIUJPHDiZjdt.gif

**Comment by xudaolong** [comment]
@Laxenade MacOS 3.3.3 已修复两个问题
