### ISSUE TITLE
UX建议

### ISSUE THREAD

**Issue by Laxenade** [oncework/codeexpander#29]
鼠标悬停在一个菜单上，菜单跳出来的速度过快了，以及上一个菜单消失的有点慢了。上述的后果就是，当鼠标在菜单栏划过会触发基本上每一个菜单，看起来有一点拥挤/乱。

**Comment by xudaolong** [comment]
@Laxenade 感觉应该还好吧 阿哈

**Comment by xudaolong** [comment]
@Laxenade 稍微加了点延迟
