### ISSUE TITLE
建议手动触发commit, 而不是在编辑时自动commit

### ISSUE THREAD

**Issue by zhezh** [oncework/codeexpander#37]
现象:
在编辑时, 会自动触发commit, 导致一次编辑, 在gist的revision history中留下许多记录

建议:
将自动保存与commit分为两步, 
在用户 手动同步到云再进行commit

**Comment by loikein** [comment]
+1，似乎是默认上传（commit），但不是默认下载（pull），就有点烦，希望都能够设置。

**Comment by xudaolong** [comment]
@loikein 好的

**Comment by xudaolong** [comment]
@zhezh @loikein 3.5.1 在
![image](https://user-images.githubusercontent.com/9654838/87058913-41bd3780-c23b-11ea-976a-c51d7f506982.png)可设置
