### ISSUE TITLE
输出 CODEEXPANDER_CLIPBOARD 时奇怪的行为

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#4]
![image](https://user-images.githubusercontent.com/20874963/54964937-570c4500-4fa9-11e9-9698-4aeff33dd4a5.png)
结果
![image](https://user-images.githubusercontent.com/20874963/54964970-7dca7b80-4fa9-11e9-9195-31f2948b5b7d.png)

![image](https://user-images.githubusercontent.com/20874963/54964957-67242480-4fa9-11e9-95c0-326c25865ff0.png)
结果：
![image](https://user-images.githubusercontent.com/20874963/54964962-730fe680-4fa9-11e9-8028-1a7d790fda35.png)

使用 `CODEEXPANDER_CLIPBOARD` 的时候输出会带上引号，强烈建议把引号去了

**Comment by xudaolong** [comment]
@Macr0phag3 👌这个优先更新

**Comment by xudaolong** [comment]
@Macr0phag3 热更新至2.7.5修复此BUG.
