### ISSUE TITLE
尝试登陆github的时候，发现所有的snippets都没了

### ISSUE THREAD

**Issue by codereason** [oncework/codeexpander#41]
之前一直是作为一个代码片段管理软件来用，也没有登陆过github。因为准备换电脑了，想看看能不能同步，结果授权登陆github之后，发现所有的snippets都不见了。请问有恢复的办法吗?
![image](https://user-images.githubusercontent.com/22554322/87110548-e2424480-c299-11ea-8e56-5df4c9d17a06.png)

**Comment by xudaolong** [comment]
你再点击一下全部同步试一下？ 可能网络卡了 
![image](https://user-images.githubusercontent.com/9654838/87112931-b7f38580-c29f-11ea-8876-c3065bcbe19c.png)

**Comment by xudaolong** [comment]
@codereason ```之前一直是作为一个代码片段管理软件来用，也没有登陆过github``` 之前没登陆过？？？

**Comment by codereason** [comment]
> @codereason `之前一直是作为一个代码片段管理软件来用，也没有登陆过github` 之前没登陆过？？？

之前确实没登陆过。刚才更新到release最新的版本，启动发现代码段都恢复了，多谢。

**Comment by xudaolong** [comment]
@codereason 好的呀 欢迎体验~ 不赞助一波作者吗? (#^.^#)
