### ISSUE TITLE
用了好久了，有些地方体验需要提升一下

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#45]
1. 同步片段的时候建议不要实时同步，新增一个按钮，编辑完了再点同步。因为实时同步似乎会出现很奇怪的 bug，什么情况都有，比如我重命名脚本的后缀 sh -> py，会出现 2 个同名不同后缀的文件。然后软件运行的时候运行的是 sh 后缀的文件，我只能删除这个sh脚本，再新建一个。并且就算我点击删除，sh 脚本也不会被删掉...
2. 有时候运行速度很缓慢，输入短语之后半天才会替换成指定的内容
3. 建议全部同步的时候，先把片段存在内存里，不要成功一个保存一个，若出现异常那么同步进行了一半，会有各种问题。昨天在我的 windows 主机上安装了 codeexpander，同步的时候提示成功，再次同步提示片段损坏，也不知道怎么恢复，我只能退出登录之后重新全部同步。
4. 搜索框的逻辑很奇特：
![image](https://user-images.githubusercontent.com/20874963/90848167-c654b700-e39e-11ea-9968-5aac9913c592.png)
似乎是在文件名里搜索的，应该是在片段的备注里搜索比较合理？

有些问题不好排查，因为不是很经常出现。作者如有精力，想办法解决一下。至于短语大小写不好加就不用加了，小功能无所谓，主要是整体的体验还需要提升一下~

环境：
macos mojave 10.14.6
windows 10

**Comment by xudaolong** [comment]
嘻嘻 我又来了
1. 不是实时同步的，内部是你停止编辑固定秒就更新，如果你继续编辑，他会重新计算时间的。bug的话 我要找找看。
2. =。=这个要debug一下。
3. 同步提示片段损坏，一般情况是正在下载中，过会重新点击就号，如果文件多的话，弱网情况，有一定几率下载不了，应该加个重新下载机制或者限制批量下载数量，分批更新，这样会慢。
4. 搜索内容包含，文件名，文件内容，文件描述，本来只是名字的，后台有个粉丝要加上的。0.0.（我是无辜的（o´・ェ・｀o））

最近比较忙，晚点更新一波。

**Comment by Macr0phag3** [comment]
好。

能不能在出问题的时候给个提示和初步的解决办法，现在出问题了我也不知道该怎么处理。

如果现在搜索逻辑包含文件内容的话，你看我给的图是搜不出来那个片段的，这应该是 bug 了

**Comment by xudaolong** [comment]
@Macr0phag3 我内置一个帮助吧 之后直接打“？”就呼出一个帮助栏？

像3， 你可以选择那个损坏的片段， 然后直接点击， 就可以了。
![image](https://user-images.githubusercontent.com/9654838/90849607-3add2500-e3a2-11ea-937d-bacc9edb6a7f.png)

**Comment by Macr0phag3** [comment]
帮助栏也行。

损坏的话有提示是哪个片段损坏了吗？我昨天好像没注意到

**Comment by xudaolong** [comment]
@Macr0phag3 有啊 就你点击的那个片段就是损坏的

**Comment by Macr0phag3** [comment]
没懂，是点击的片段如果有损坏会提醒是吗？

**Comment by xudaolong** [comment]
@Macr0phag3 对 是的呀

**Comment by Macr0phag3** [comment]
ok
