### ISSUE TITLE
simple text expansion question

### ISSUE THREAD

**Issue by hfcheng66** [oncework/codeexpander#46]
I installed the mac version and setup a test-group, create a 'Text' snippet like below. Click the 'Run' button the preview is correct. However if I type the abbreviate keyword 'test1' and space in other application, it doesn't expand at all. Is there any setting I need to enable? 

![image](https://user-images.githubusercontent.com/38507451/91361773-a36f3c00-e7be-11ea-8682-516f34438b10.png)

**Comment by xudaolong** [comment]
@hfcheng66 
Do you have a configuration based here? https://codeexpander.com/en/views/introduce/installation.html#installation

**Comment by hfcheng66** [comment]
> @hfcheng66
> Do you have a configuration based here? https://codeexpander.com/en/views/introduce/installation.html#installation
> 
> and restart applition again.

Yes that was setup already and also restarted codeexpander. however the text replacement doesn't happen.
![image](https://user-images.githubusercontent.com/38507451/91467487-40c97f00-e856-11ea-95d2-19c8772fbd0c.png)

tested in vs code:
![image](https://user-images.githubusercontent.com/38507451/91467567-58a10300-e856-11ea-95b0-b706553bb805.png)

**Comment by xudaolong** [comment]
![测试-001](https://user-images.githubusercontent.com/9654838/91515180-23aab400-e91b-11ea-9de2-0cb81638ae64.gif)

Everything's fine on my side, even if I'm on Windows 10. Would you mind offering your macos version? and provide me with the following pictures.

![image](https://user-images.githubusercontent.com/9654838/91515300-72584e00-e91b-11ea-85f8-d4dc497cd305.png)

![image](https://user-images.githubusercontent.com/9654838/91515323-7e441000-e91b-11ea-99f2-b8777d85d9fc.png)

![image](https://user-images.githubusercontent.com/9654838/91515333-84d28780-e91b-11ea-8c53-3a7258798acf.png)

@hfcheng66
