### ISSUE TITLE
Tag 不一致的问题

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#5]
见图：

![image](https://user-images.githubusercontent.com/20874963/55044004-a61eac80-5073-11e9-9745-585152f38641.png)

![image](https://user-images.githubusercontent.com/20874963/55044018-acad2400-5073-11e9-8724-d54bb58f9957.png)

**Comment by Macr0phag3** [comment]
似乎缺少的那个 tag 是空的那个 tag

**Comment by xudaolong** [comment]
@Macr0phag3  专业测试人员。嘿嘿嘿。晚上回去Fix。很快噶。感谢。👌

**Comment by xudaolong** [comment]
@Macr0phag3 已更新。
