### ISSUE TITLE
在弹出的输入框中使用键盘确认会造成重复输出

### ISSUE THREAD

**Issue by zhangyang94s** [oncework/codeexpander#52]
版本：windows 3.5.4
运行环境：windows10 教育版
如图所示。
同时还有一些优化建议。
1. 刚开始呼出FillInMoel弹窗的时候，焦点应该默认在第一个可输入/选择的地方，目前是无焦点，需要多按一次Tab。
2. 同名的变量，Tab切换的时候应该能够忽略，这样可以减少键盘输入次数。对于重度依赖键盘的人来说，体验会好很多
3. 建议回车直接就对Model完成返回，不需要再一个个切到其他的输入框中。因为本身输入框不需要回车确认，而下拉选择菜单也不需要确认体验更好
![codeexpenderBug](https://user-images.githubusercontent.com/3949965/99357630-2f3cc400-28e7-11eb-9674-67521053e0cc.gif)

**Comment by xudaolong** [comment]
1和3 已处理好，待发布
