### ISSUE TITLE
建议整合至Alfred Workflow中

### ISSUE THREAD

**Issue by hezhefly** [oncework/codeexpander#54]
建议整合至Alfred Workflow中，这样可以更加方便的触达code expander

**Comment by xudaolong** [comment]
@hezhefly 已有悬浮搜索 这个优先级不高哈
<img width="500" alt="image" src="https://user-images.githubusercontent.com/9654838/157684391-ccbbc1d6-27d9-46b2-a0dc-841732333ae5.png">
