### ISSUE TITLE
没有检索到application以外的 app  

### ISSUE THREAD

**Issue by dbeenlee** [oncework/codeexpander#55]
![image](https://user-images.githubusercontent.com/4352949/100325222-4a07ea80-3003-11eb-8ab8-0648386f61d4.png)

比如Toolbox App 下载的Jet Brains系列软件 就不在application文件夹里   但确实又需要这个软件配合编码  
目前解决方案是 排除法  弊端就是安装新的软件就要手动排除   

诉求： 希望能够检索到非application文件夹里的 app

**Comment by xudaolong** [comment]
@dbeenlee  添加手动额外路径，MacOS 专属, v4.0.0
<img width="655" alt="image" src="https://user-images.githubusercontent.com/9654838/154041014-314bfc90-d8f1-45a4-aecb-415a22ee5624.png">
