### ISSUE TITLE
Python 的版本问题

### ISSUE THREAD

**Issue by Macr0phag3** [oncework/codeexpander#6]
你应该是使用 Python2.x 的语法来完成执行脚本的任务的，因为在安装 pyenv 并设置全局版本为 3.x 的情况下，执行脚本会报以下错误：
![image](https://user-images.githubusercontent.com/20874963/55062020-10554280-50b0-11e9-888d-06f895eda2bd.png)

这个库应该是 2.x 才有的，3.x 把它放到 urllib.parse 里去了。建议兼容一下。

并且说实话 2.x 注定要被淘汰，为何不用 3.x 呢？

**Comment by xudaolong** [comment]
当初考虑大多数的默认安装都是2.7，应该加个兼容的。

**Comment by xudaolong** [comment]
@Macr0phag3 2.7.8版本可以修改路径了，需要重新同步脚本，切换Python 2/3 之间版本的时候也是.
