### ISSUE TITLE
希望增加一个一键格式化代码

### ISSUE THREAD

**Issue by seth-shi** [oncework/codeexpander#62]
增加一个一键格式化代码

**Comment by xudaolong** [comment]
@seth-shi 这个不同语言 格式化的逻辑不一样 emm

**Comment by xudaolong** [comment]
@seth-shi 你常用是什么语言 我可以特殊处理下

**Comment by seth-shi** [comment]
我觉得应该有现成的方案, 你看一下 [https://prettier.io/](https://prettier.io/)
我想要的可能是压缩之后的代码, 帮我处理好
1. 自动换行
2. 自动缩进
3. 左右大括号可以选择是否换行

****

还有另一个笔记的需求就是, 应该是 github 和 gitee 同时登录, 而不是只有一个平台(一个主用, 另一个备份)

thx
