### ISSUE TITLE
希望能增加html预览功能。

### ISSUE THREAD

**Issue by soiieking** [oncework/codeexpander#64]
平时写静态页笔记多，希望作者能增加一个静态页面的预览功能。需求如下：

### 1.能够在同一界面编辑html  css  js代码。

类似于这个：https://playcode.io/

### 2.支持sass

如果能实现需求1

希望在编写css的时候能够支持scss或者less，这样就能 将某些样式存到变量里，比如我做了一个登陆表单，将边距，圆角，颜色什么的存到变量里，下次复用的时候，修改下变量值，拿过来一粘贴。就会方便很多。如此一来，当存储的代码片段足够多的时候，或许做页面会像搭积木一样简单起来。

**Comment by xudaolong** [comment]
#133
