### ISSUE TITLE
3.5.9版本，win系统下，后台任务栏运行，无法打开主界面

### ISSUE THREAD

**Issue by huizhizhao** [oncework/codeexpander#66]
![image](https://user-images.githubusercontent.com/21138860/122722480-5d7ee980-d2a4-11eb-8a0c-8881cbbdd695.png)
点击红色按钮，程序后台运行

![image](https://user-images.githubusercontent.com/21138860/122722591-7be4e500-d2a4-11eb-92a4-426033159f0a.png)
右键任务栏图标，点击“显示CodeExpander”，无法显示主界面，希望左键任务栏图标唤醒

**Comment by chengyiqun** [comment]
同遇到一样问题

**Comment by xudaolong** [comment]
@huizhizhao @chengyiqun 下周我抽个时间改改

**Comment by xudaolong** [comment]
@huizhizhao 已修复 v4.0.0
