### ISSUE TITLE
[win平台_3.5.9版本] 代码片段自动上传问题

### ISSUE THREAD

**Issue by htycode** [oncework/codeexpander#67]
平台:win
版本:3.5.9

编辑好的代码片段
有时能自动上传成功
有时就会显示显示下面这种情况, 上传失败
![image](https://user-images.githubusercontent.com/49477889/122740680-c96a4d80-d2b6-11eb-9bc8-f77bacdc55a7.png)

**Comment by xudaolong** [comment]
@htycode 大多数是网络原因，已添加了一分钟的重试机制，在v4.0.0
