### ISSUE TITLE
[win平台_3.5.9版本] 悬浮搜索栏-样式排版问题

### ISSUE THREAD

**Issue by htycode** [oncework/codeexpander#68]
如下图所示
搜索出来的代码片段名称显示的字数太少
看不到完整的名称
希望在样式排版上修改一下
能显示出完整的名称
![image](https://user-images.githubusercontent.com/49477889/122741851-f703c680-d2b7-11eb-957e-6600780835e6.png)

**Comment by xudaolong** [comment]
@htycode okk 我优化一下

**Comment by xudaolong** [comment]
@htycode 适量调整，若太长会显示两行.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/9654838/153830626-b54472f5-1076-464c-b500-b7ac1b5a8bea.png">
