### ISSUE TITLE
[win平台_3.5.9版本]悬浮搜索栏-希望添加筛选功能

### ISSUE THREAD

**Issue by htycode** [oncework/codeexpander#69]
希望悬浮搜索栏能添加一个
像这种筛选搜索范围的功能

因为每次在悬浮搜索栏搜索时, 总是搜索到很多无关的代码片段
其实我就想搜索文件名中包含的关键字
![image](https://user-images.githubusercontent.com/49477889/125621250-a44c96d5-0a7d-4d40-8cbc-9315488c46ca.png)

**Comment by xudaolong** [comment]
@htycode v4.0.0 已完成，待发布
<img width="500" alt="image" src="https://user-images.githubusercontent.com/9654838/153824603-0ea77cfa-8c11-49e9-9704-382a04a64457.png">
