### ISSUE TITLE
建议调短一些提示的显示时长

### ISSUE THREAD

**Issue by UniqueSimon** [oncework/codeexpander#7]
比如删除时“提示本地片段已损坏，请从云端更新”，一直挡着主要按钮，要等好久。

<img width="1200" alt="Snipaste-09-30-10" src="https://user-images.githubusercontent.com/26346635/55123123-5eb02300-513c-11e9-9aa9-ecef01b504ec.png">

**Comment by xudaolong** [comment]
@UniqueSimon 我将考虑转移到其他位置 右下角或者右上角。😸

**Comment by xudaolong** [comment]
@UniqueSimon 已经移开了阻挡的位置了。热更新更新下。
