### ISSUE TITLE
希望能给MD 的code美化一下

### ISSUE THREAD

**Issue by mcblog** [oncework/codeexpander#70]
![微信截图_20210910104617](https://user-images.githubusercontent.com/30430287/132791234-e4338240-5a3e-4825-822c-8e9d48a097fa.png)

大概看了几个特别舒服的：
![微信截图_20210910104853](https://user-images.githubusercontent.com/30430287/132791472-a8f5d99a-61cd-4794-a7c0-32a636283b6d.png)
![微信截图_20210910104949](https://user-images.githubusercontent.com/30430287/132791552-8b71ff5a-0eda-483a-8408-df0cc93f36f7.png)
![微信截图_20210910105406](https://user-images.githubusercontent.com/30430287/132791920-9ffb400c-9f02-4422-989d-3809b450ef96.png)

仅提供参考

 谢谢

**Comment by xudaolong** [comment]
#133
