### ISSUE TITLE
希望可以支持自定义精简界面

### ISSUE THREAD

**Issue by Mruos** [oncework/codeexpander#72]
希望有个纯净版模式开启的开关。。。就是可以自己选择是否隐藏掉【未配置】和代码编辑区上面的【代码片段】、【指令】、【运行】、【Fill-ins一行的内容】等等这些辅助功能。因为这些辅助功能用不着，我就想一个干净的界面看代码片段。。。
[](http://images.burnlord.com/s/app/bibicenter/20210923134225.png)

如果可以代码区的有个快捷键可以格式化代码就更好了。。。

谢谢老大

**Comment by Mruos** [comment]
还有，片段没写描述的提示：这个人很懒，什么都没写。如果没有可以隐藏掉吗。。。。不然很多没写，这句话在片段列表里就大量存在

**Comment by xudaolong** [comment]
@Mruos 更新 v 4.0.0
<img width="630" alt="image" src="https://user-images.githubusercontent.com/9654838/154024854-167a3e74-c9bd-41bb-aec0-889e8f529dab.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9654838/154024913-6dd9abcc-d544-4009-91d4-53dcb85de2af.png">
