### ISSUE TITLE
版本功能优化几个小建议

### ISSUE THREAD

**Issue by 523219809** [oncework/codeexpander#74]
现有的BUG：
1、保存代码段的时候修改下名称在保存就变成了另一个代码段了多保存几次就好几份了。
2、打开的代码段点关闭应该是关闭页签而不是删除，目前点击这个关闭会弹出俩功能：
![image](https://user-images.githubusercontent.com/7053590/146677927-32bd2813-3955-4bb0-b47b-c019cdf87f10.png)
3、用QQ登录码云后主程序一直在转圈不知道是什么问题，后来我是用账号登录的才行。
4、用码云登录的时候应该只能选私密，也就是是否公开就得是禁用的，码云就不支持公开的。
增加新功能：
1、增加选择代码类型的功能现在每次都得自己选，建议增加默认支持的一大堆代码自己也可以添加小众的代码类型。
     注：按照使用顺序来排列代码类型，第一个默认的永远都是最后一次使用的。
2、新建代码段的这个窗口过于复杂本身就是从代码分类过来的建议放一些有用的，比如只需要输入标题和内容，不要在打开后在输入内容了。
3、新建的页面俩按钮放的太小了最好给他占满程序员一般眼神都不好使。
4、主界面最上面的那些按钮没用的都挪到别的地方吧一般来说那玩意应该没人用。

**Comment by xudaolong** [comment]
1、保存代码段的时候修改下名称在保存就变成了另一个代码段了多保存几次就好几份了。
- 已修复

2、打开的代码段点关闭应该是关闭页签而不是删除，目前点击这个关闭会弹出俩功能：
- 已修复

3、用QQ登录码云后主程序一直在转圈不知道是什么问题，后来我是用账号登录的才行。
- 已修复

4、用码云登录的时候应该只能选私密，也就是是否公开就得是禁用的，码云就不支持公开的。
- 啊对，我也发现了。算了，保留先把。

增加新功能：
1、增加选择代码类型的功能现在每次都得自己选，建议增加默认支持的一大堆代码自己也可以添加小众的代码类型。
注：按照使用顺序来排列代码类型，第一个默认的永远都是最后一次使用的。

- 加了1000多种类型，你开心吗？
<img width="306" alt="image" src="https://user-images.githubusercontent.com/9654838/154086121-2371dc0e-3673-4838-b0e2-daf6f5c86906.png">


2、新建代码段的这个窗口过于复杂本身就是从代码分类过来的建议放一些有用的，比如只需要输入标题和内容，不要在打开后在输入内容了。
- 其实不用填任何东西就能直接生成，你试试，都是可选选项来的

3、新建的页面俩按钮放的太小了最好给他占满程序员一般眼神都不好使。
- 放到一处了，不满意就给我设计稿吧。

<img width="200" alt="image" src="https://user-images.githubusercontent.com/9654838/154086428-586f8a98-71d3-4e8a-9939-96e8544cd3bd.png">


4、主界面最上面的那些按钮没用的都挪到别的地方吧一般来说那玩意应该没人用。
- 重新编排了。
