### ISSUE TITLE
又用了一会提几个优化类的小功能，不耽误使用但是细节加到一块就有点影响了

### ISSUE THREAD

**Issue by 523219809** [oncework/codeexpander#75]
在提几个优化功能：
1、右侧的这个目前是用的页签组件但是完成的不是页签的功能所以最好和这个软件这样点开几个片段就打开几个，要么就别用页签组件：
![image](https://user-images.githubusercontent.com/7053590/146678924-49804ebd-8ccc-412d-876f-817272a1438d.png)
2、右下角的托盘现在左右都是弹出菜单有点反人类左键点击得打开主程序。
3、头像太丑了不能自己修改吗不能修改就设置一些默认的也可以啊。
4、这个未配置显示到列表上不太好吧，这玩意如果只是单纯的管理代码片段或许都是空的：
![image](https://user-images.githubusercontent.com/7053590/146679390-6c82b78a-a3a5-44d1-a43c-ba37dad3b12e.png)
5、目前的版本后缀如果是.JAVA的话是只能识别出语言但是高亮的话无法显示。
![image](https://user-images.githubusercontent.com/7053590/146679477-fc475be8-ccec-4b19-899d-fb1fa44b0009.png)
6、重启应用这个地方点击后太死板了得卡半天，能不能让他转圈然后在自己把自己弄死，强迫症的我看着就想掐死他。
7、图标的话最好放大点现在太小气了就一个小圈圈。
8、我点这个收藏夹竟然弹出添加分组的这个应该是事件没控制住吧
![image](https://user-images.githubusercontent.com/7053590/146679581-f06b7fff-a0f4-4d24-acdb-95eb8802d6a7.png)
9、点击偏好设置后这里感觉少了一个标题，强迫症有点看不过去
![image](https://user-images.githubusercontent.com/7053590/146679653-50f10acd-fae1-4d96-a1ef-bdd62df8babe.png)
10、偏好设置的页面有点过度包装了内容太少了占了这么多页签。

**Comment by xudaolong** [comment]
在提几个优化功能：
1、右侧的这个目前是用的页签组件但是完成的不是页签的功能所以最好和这个软件这样点开几个片段就打开几个，要么就别用页签组件：
- 这个一开始定义就是一个片段多个子片段【🙅‍♂️】

2、右下角的托盘现在左右都是弹出菜单有点反人类左键点击得打开主程序。
- 已修复

3、头像太丑了不能自己修改吗不能修改就设置一些默认的也可以啊。
- logo也丑吗，啊这，登录就能换自己头像了。

4、这个未配置显示到列表上不太好吧，这玩意如果只是单纯的管理代码片段或许都是空的：
- 加了一个纯代码管理模式
<img width="337" alt="image" src="https://user-images.githubusercontent.com/9654838/154085203-b10fd3b9-cadd-4542-a421-fc5e48e6c5b7.png">


5、目前的版本后缀如果是.JAVA的话是只能识别出语言但是高亮的话无法显示。
- 这个好像是，另起一个issue吧【todo】

6、重启应用这个地方点击后太死板了得卡半天，能不能让他转圈然后在自己把自己弄死，强迫症的我看着就想掐死他。
- 不是很明白。【😯】

7、图标的话最好放大点现在太小气了就一个小圈圈。
- 哦

8、我点这个收藏夹竟然弹出添加分组的这个应该是事件没控制住吧
- 已修复

9、点击偏好设置后这里感觉少了一个标题，强迫症有点看不过去
- 保留。【☺️】

10、偏好设置的页面有点过度包装了内容太少了占了这么多页签。
- 重新归类了下。
-
