### ISSUE TITLE
界面上的一些改进功能：

### ISSUE THREAD

**Issue by 523219809** [oncework/codeexpander#76]
1、激活软件的功能建议放到偏好设置的最后一个页签里面，这样就有俩入口了。
2、如果已经设置了激活码主界面上的这个就不要显示了碍眼。
3、左侧的代码分类如果能有右键弹出菜单的功能就好了。
4、另外功能区域的最小化，最大化，关闭如果能设置左右位置就更好了，windows的用户还是喜欢在右侧。
5、好像还是缺少一个导入导出的功能方便备份和导入数据。
6、复制代码段的时候就没必要打开了吧感觉打开就是多此一举。

**Comment by xudaolong** [comment]
1、激活软件的功能建议放到偏好设置的最后一个页签里面，这样就有俩入口了。
- 保留主界面啦

2、如果已经设置了激活码主界面上的这个就不要显示了碍眼。
- 同上

3、左侧的代码分类如果能有右键弹出菜单的功能就好了。
<img width="253" alt="image" src="https://user-images.githubusercontent.com/9654838/154082058-6aedfaf2-28e2-422d-8ff6-09491d9862b6.png">


4、另外功能区域的最小化，最大化，关闭如果能设置左右位置就更好了，windows的用户还是喜欢在右侧。
- 可

5、好像还是缺少一个导入导出的功能方便备份和导入数据。
- 导入类型未定，需要自定义格式，最好还是同步到gist或者码云。

6、复制代码段的时候就没必要打开了吧感觉打开就是多此一举。
- 已修正
