### ISSUE TITLE
这个运行按钮如果选的是代码段不应该显示吧，就算显示按钮名称应该也得叫预览而不是运行

### ISSUE THREAD

**Issue by 523219809** [oncework/codeexpander#77]
这个运行按钮如果选的是代码段不应该显示吧，就算显示按钮名称应该也得叫预览而不是运行。
![image](https://user-images.githubusercontent.com/7053590/146697628-57f9e132-dbba-42cd-8e1a-59c57e266e2e.png)

**Comment by xudaolong** [comment]
@523219809 这个是切换片段的效果，已在4.0更改为预览
