### ISSUE TITLE
在Xshell中使用“指令”不能正常粘贴

### ISSUE THREAD

**Issue by HoyDom** [oncework/codeexpander#78]
实测在Xshell中输入"指令"不能正常粘贴代码片段，在文档中则正常。

**Comment by HoyDom** [comment]
https://user-images.githubusercontent.com/96682852/147408831-e159f479-adf0-4c68-b39d-788c11dda4f7.mp4

**Comment by xudaolong** [comment]
@HoyDom 在4.0.3中已经发布，该功能
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9654838/155849122-8c582458-d060-4729-9828-1cba13b1bcb0.png">
