### ISSUE TITLE
组合键option+1的用途是什么？

### ISSUE THREAD

**Issue by UniqueSimon** [oncework/codeexpander#8]
无意中发现按option+1会弹出一个空白的fillin窗口，翻了翻文档似乎没有相关介绍

<img width="550" alt="Snipaste-09-46-46" src="https://user-images.githubusercontent.com/26346635/55123987-99678a80-513f-11e9-82a4-b1ce01ddc82b.png">

**Comment by xudaolong** [comment]
@UniqueSimon  https://once.work/support/fill-in 这个作用的。你了解一下

**Comment by UniqueSimon** [comment]
@xudaolong 但是我没有设置这个快捷键，而且弹出的fillin并没有内容

**Comment by xudaolong** [comment]
@UniqueSimon 这个是用作预加载窗口作用的，只有设定片段并发出指令才有内容
