### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by Yuelioi** [oncework/codeexpander#82]
1.字体太小了。而且没找到在哪里设置大小。4K屏2K屏用起来很难受（重要）。
2.目前代码片段是标签式的，很方便。但是一旦一个分组的代码段变多（15+）看起来就会很乱。可以增加个切换把代码片段列表信息简化（或者自适应切换，比如大于10个会简化），只显示名称、复制、分享，而不显示私有、配置等信息（比较重要）
3.支持导入导出（比较重要）
4.缩略语模块支持搜索，或者有个单独的缩略语清单，这个可以用缩略语作为条目名就行（一般）
5.暗黑主题（有人提过了）或者开发自定义css接口（这个不算刚需）
6.与VSC等编辑器联动（这个不算刚需）

**Comment by xudaolong** [comment]
@Yuelioi  1，2，3点可以优先处理哈，4是已有功能
<img width="133" alt="image" src="https://user-images.githubusercontent.com/9654838/157357646-8e2e8f9c-3f0c-4f74-9784-1d41021b1fb1.png">
