### ISSUE TITLE
创建自定义组合键后，无法定位到自定义快捷键所在行光标最右侧

### ISSUE THREAD

**Issue by light499960904** [oncework/codeexpander#86]
如图：
创建自定义组合键后，无法定位到自定义快捷键所在行光标最右侧
![image](https://user-images.githubusercontent.com/27767203/161363643-8e65ef35-4038-4fa6-a18c-7c9d0a1ee932.png)

**Comment by xudaolong** [comment]
@light499960904 字体问题 稍后修复

**Comment by xudaolong** [comment]
@light499960904 已解决 待发布
<img width="431" alt="image" src="https://user-images.githubusercontent.com/9654838/161375688-5293ae9d-68ce-437a-a9e3-9bd98e8b45c1.png">
