### ISSUE TITLE
界面字体锐化严重，希望能允许用户自定义界面上的字体设置

### ISSUE THREAD

**Issue by light499960904** [oncework/codeexpander#87]
希望能允许用户自定义界面上的字体设置：
可以设置全局，也可以设置局部（代码区、功能区）

**Comment by xudaolong** [comment]
@light499960904 提供自定义CSS 待发布
<img width="680" alt="image" src="https://user-images.githubusercontent.com/9654838/161387356-29fec1b3-eda0-478d-be98-d20f91bae454.png">
