### ISSUE TITLE
组别设置界面，生效的应用程序列表处没有标头，不知道哪边是生效，哪边是不生效

### ISSUE THREAD

**Issue by light499960904** [oncework/codeexpander#88]
![image](https://user-images.githubusercontent.com/27767203/161363868-12b6007f-866c-4062-83e0-21178238fe3c.png)

**Comment by xudaolong** [comment]
@light499960904 仅右侧应用使用哈
<img width="445" alt="image" src="https://user-images.githubusercontent.com/9654838/161363936-50bf1d0e-3935-4453-ad4a-20d25e898fb0.png">

**Comment by light499960904** [comment]
这边的话希望能加强一下提示

**Comment by xudaolong** [comment]
@light499960904  提示了一下哈
<img width="530" alt="image" src="https://user-images.githubusercontent.com/9654838/161367432-2684e699-1265-44cb-930b-2eeb2a3f7d91.png">
