### ISSUE TITLE
组别设置页面，应用程序查询框希望支持模糊查询，对大小写不敏感

### ISSUE THREAD

**Issue by light499960904** [oncework/codeexpander#89]
![image](https://user-images.githubusercontent.com/27767203/161363968-b79b38a4-a36c-4ad5-b9bc-1a0444f7ecd9.png)

**Comment by xudaolong** [comment]
@light499960904  下个版本发。
<img width="487" alt="image" src="https://user-images.githubusercontent.com/9654838/161367218-a1eb2cf7-8b38-4307-b820-d50d89e9c564.png">
