### ISSUE TITLE
无法在分组配置中添加应用程序

### ISSUE THREAD

**Issue by hsingll** [oncework/codeexpander#9]
直接搜索似乎不行，拖放也不行。

**Comment by xudaolong** [comment]
@UniqueSimon 只支持自动加载 MacOS 的application列表中的应用， Windows版本还没支持。待解决

**Comment by UniqueSimon** [comment]
@xudaolong 我的系统是MacOS 10.14.3，没有加载application
<img width="1440" alt="Snipaste-10-43-32" src="https://user-images.githubusercontent.com/26346635/55126060-dedb8600-5146-11e9-8c0f-0e3958517f27.png">

**Comment by xudaolong** [comment]
@UniqueSimon 你删除掉 `${require('os').tmpdir()}/work.once`(像`/var/folders/md/xwycc8l5495ccr38q8j0kc400000gp/T`) 并重启能否解决问题？

**Comment by UniqueSimon** [comment]
@xudaolong 删除后${require('os').tmpdir()}/work.once重新打开应用还是没有，${require('os').tmpdir()}/work.once又生成了，里面有各个应用的iconset

**Comment by xudaolong** [comment]
@UniqueSimon 好的，我回去复现一下，我工作机是10.13是没问题的。

**Comment by Macr0phag3** [comment]
macOS v10.14.3 实测不行

**Comment by xudaolong** [comment]
@hsingll @Macr0phag3 已经可以了 测试在10.15.3 通过 有空试试
