### ISSUE TITLE
Windows下，在顶部栏位右键显示出来的选单事件全部失效，无法点击

### ISSUE THREAD

**Issue by light499960904** [oncework/codeexpander#90]
![image](https://user-images.githubusercontent.com/27767203/161364032-b24bd0b3-951b-4dcf-b9a6-a8ea374d6d12.png)

**Comment by light499960904** [comment]
建议要么屏蔽，要么重写下Electron的事件

**Comment by xudaolong** [comment]
@light499960904 这个暂时无法处理 因为是electron的BUG issue: https://github.com/electron/electron/issues/26726
