### ISSUE TITLE
希望能增加一个延迟匹配的功能，目的是输入相同前缀但又有区别的内容

### ISSUE THREAD

**Issue by niushuai233** [oncework/codeexpander#93]
eg:
dict-test-route
dict-test-route-line

那么第二个永远无法输入，虽然可以将key设置成不同的，但是他就是一个组的，所以希望作者考虑一下是否延迟1s匹配，
当然这个配置可以由用户是否开启，以及延迟的时间都可以由设置项控制

感谢

**Comment by xudaolong** [comment]
@niushuai233 可以暂时通过免键操作, 我后面加一下这个延迟试试
<img width="596" alt="image" src="https://user-images.githubusercontent.com/9654838/168741498-a643386a-9e68-483b-b5d7-d383da5fdd56.png">
