### ISSUE TITLE
你好，我的系统是MacOS Monterey，没有预装python2.7，我安装了python3以后，在app内修改了路径无效

### ISSUE THREAD

**Issue by NavinChen** [oncework/codeexpander#94]
如题，依然提示
* 缺少软件正常使用必备环境,请自行安装 Python
路径我修改为/usr/bin/python3，不可行
python3版本：3.8.2

**Comment by xudaolong** [comment]
@NavinChen 先 `where python3`

修改后 重启看看

**Comment by NavinChen** [comment]
都不行，郁闷

**Comment by xudaolong** [comment]
@NavinChen 可以安装python2.7 试试
```
brew install kamilturek/python2/python@2
```

**Comment by NavinChen** [comment]
> @NavinChen 可以安装python2.7 试试
> 
> ```
> brew install kamilturek/python2/python@2
> ```

已经可以了，谢谢大佬
