### ISSUE TITLE
使用了下,希望能解决如下问题.

### ISSUE THREAD

**Issue by kqixiang945** [oncework/codeexpander#95]
1. 编辑器支持代码格式化.
2. 支持代码片段拖动到其他的分组.
3. 支持为代码片段打标签.
4. 支持自定义快捷键.
5. 预览可以看编辑器中代码的结果, 但是输出的时候还是保持原始的代码.
6. 标签页没有 ❎ 关闭的按钮.
7. 能支持运行更多的语言最好(比如:java)

**Comment by xudaolong** [comment]
@kqixiang945 除了 5、6，其他放 #133
