### ISSUE TITLE
希望作者能增加hover代码片段时显示用户上传的代码运行图片。

### ISSUE THREAD

**Issue by CodeEngieer** [oncework/codeexpander#96]
公司做着前后端的工作，代码量随着工作时间而增加。静态代码片段没有代码运行图片直观，希望作者能增加hover代码片段时显示用户上传的代码运行图片。具体需求如下：
1. hover代码片段时显示用户上传代码运行片段。
2. 图片可以采用url链形式
3. 片段组内能增加新的片段组以便于存储更专精部分的内容，如前端导航栏好几种效果与实现方法。

**Comment by xudaolong** [comment]
同 #64
